steps:
  - id: 'Tag, release, build'
    name: 'eu.gcr.io/hmf-build/jdk-mvn-python'
    entrypoint: 'python3'
    args: ['hmftools-build.py', '$TAG_NAME']

logsBucket: 'gs://hmf-build-logs'
timeout: 1800s
images:
  - 'eu.gcr.io/hmf-build/jdk-mvn-python'