steps:
  - id: 'Set version, release'
    name: 'maven:3.9.2-eclipse-temurin-11'
    entrypoint: 'sh'
    args: ['workspace/hmftools-build.sh', '$TAG_NAME']
timeout: 4800s
logsBucket: 'gs://hmf-build-logs'
options:
  machineType: 'E2_HIGHCPU_8'
