steps:
  - id: 'Fetch token for github'
    name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=hmftools-github-release-token --format='get(payload.data)' | tr '_-' '/+' | base64 -d > /workspace/github.token" ]
  - id: 'Fetch password for Dockerhub'
    name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=hmftools-dockerhub-password --format='get(payload.data)' | tr '_-' '/+' | base64 -d > /workspace/dockerhub.password" ]
  - id: 'Tag, release, build'
    name: 'eu.gcr.io/hmf-build/jdk-mvn-python'
    entrypoint: 'python3'
    args: ['hmftools-build.py', '$TAG_NAME']
  - id: 'Publish Docker image'
    name: 'eu.gcr.io/hmf-build/docker-tag'
    entrypoint: sh
    args: ['/workspace/docker.sh']
logsBucket: 'gs://hmf-build-logs'
timeout: 1800s
images:
  - 'eu.gcr.io/hmf-build/jdk-mvn-python'
